import type { ScenarioInputs, SliderParams, ScenarioResult, MonthlyProjection } from './types';

/**
 * Runs the commercial scenario model.
 *
 * TODO (issue #7): Replace stub projections with real model logic.
 *
 * Intended mechanics:
 *
 * Lever 1 — Existing customer suppression (existingCustomerSuppression):
 *   Suppressing existing customers from paid media reduces spend proportional
 *   to the share of budget currently hitting known customers. Freed budget is
 *   available for lever 3 reinvestment. Has a neutral-to-positive effect on
 *   new customer acquisition efficiency.
 *   Key inputs: monthlyMediaSpend, activeCustomerCount, averageOrderValue
 *
 * Lever 2 — Experimentation / CRO uplift (experimentationUplift):
 *   Applies a compounding monthly multiplier to the revenue baseline.
 *   Uncertainty band widens over the 12-month horizon.
 *   Key inputs: annualRevenue, averageOrderValue
 *
 * Lever 3 — Reinvestment of media savings (mediaReinvestmentRate):
 *   The savings generated by lever 1 are reinvested into paid media.
 *   A marginal ROAS assumption drives the resulting revenue uplift.
 *   Key inputs: the monthly saving amount derived from lever 1
 *
 * Confidence range:
 *   low  = mid × (1 - uncertaintyFactor)
 *   high = mid × (1 + uncertaintyFactor)
 *   uncertaintyFactor grows linearly from 5% in month 1 to 20% by month 12.
 *   TODO (issue #7): Validate uncertainty spread assumptions with stakeholder.
 */
export function runScenario(
  inputs: ScenarioInputs,
  sliders: SliderParams,
): ScenarioResult {
  const projections: MonthlyProjection[] = [];

  for (let month = 1; month <= 12; month++) {
    // TODO (issue #7): Replace with real per-lever calculations.
    const mid = inputs.annualRevenue / 12;
    const uncertaintyFactor = 0.05 + (month - 1) * (0.15 / 11);

    projections.push({
      month,
      low: mid * (1 - uncertaintyFactor),
      mid,
      high: mid * (1 + uncertaintyFactor),
    });
  }

  return { projections };
}
